host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: default
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest


# https://thoth-station.ninja/docs/developers/kebechet/managers.html#available-managers
managers:
  - name: info
    configuration:
      enabled: true
  - name: label-bot
    configuration:
      enabled: true
  - name: pipfile-requirements
    configuration:
      enabled: true
  - name: thoth-advise
    configuration:
      enabled: true
  - name: thoth-provenance
    configuration:
      enabled: true
  - name: update
    configuration:
      enabled: true
  - name: version
    configuration:
      enabled: true
