- name: Snyk
  uses: snyk/actions@0.3.0

name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
          
name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
        with:
          command: monitor

name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: snyk/actions/setup@main
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
          
env:
  SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}

name: Example workflow for dotNET using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
          
name: Example workflow for Golang using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
          
name: Example workflow for PHP using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/php@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
   
name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
 
name: Example workflow for Python using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}

name: Example workflow for Scala using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/scala@main
        env:
          SNYK_TOKEN: ${{9e3520d8-acb1-4037-a2e9-fff7301b7655}}
          
